version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: daily
      time: "09:00"
      timezone: Asia/Tokyo
