# syntax=docker/dockerfile:1

ARG NODE_VERSION=22
ARG RUBY_VERSION=3.3
ARG CANVAS_HOME=/opt/canvas

FROM node:${NODE_VERSION}-bookworm-slim AS node

FROM ruby:${RUBY_VERSION}-bookworm AS builder

ARG YARN_VERSION=1.22.22
ARG GIT_BRANCH=prod
ARG CANVAS_HOME

COPY --from=node /usr/local/bin/node /usr/local/bin
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN <<EOF
ln -s /usr/local/bin/node /usr/local/bin/nodejs
ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

apt-get update
apt-get install -y --no-install-recommends \
    libidn-dev \
    libxmlsec1-dev

npm update -g npm
npm install -g yarn@${YARN_VERSION}
EOF

ADD https://api.github.com/repos/instructure/canvas-lms/git/refs/heads/${GIT_BRANCH} /dev/null
RUN git clone -b ${GIT_BRANCH} --depth 1 https://github.com/instructure/canvas-lms.git ${CANVAS_HOME}

WORKDIR ${CANVAS_HOME}

RUN <<EOF
yarn config set network-timeout 600000
yarn config set network-concurrency 1
yarn install --pure-lockfile

bundle install
bundle exec rake canvas:compile_assets_dev

rm -rf \
    .git \
    .github \
    .storybook \
    .vscode \
    build \
    doc \
    docker-compose \
    hooks \
    inst-cli \
    jest \
    log/* \
    node_modules \
    patches \
    tmp/* \
    ui \
    ui-build
rm \
    .codeclimate.yml \
    .dependency-cruiser.js \
    .devcontainer.json \
    .dive-ci \
    .dockerignore \
    .editorconfig \
    .eslintignore \
    .eslintrc.js \
    .git-blame-ignore-revs \
    .gitignore \
    .gitmessage \
    .groovylintrc.json \
    .i18nignore \
    .i18nrc \
    .irbrc \
    .lintstagedrc.js \
    .npmrc \
    .nvmrc \
    .prettierrc \
    .rspec \
    .rubocop.yml \
    .sentryignore \
    .stylelintrc \
    CONTRIBUTING.md \
    COPYRIGHT \
    Dockerfile* \
    Jenkinsfile* \
    LICENSE \
    README.md \
    SECURITY.md \
    code_of_conduct.md \
    config/*.yml.* \
    docker-compose* \
    gulpfile.js \
    issue_template.md \
    jest.config.js \
    karma.conf.js \
    package.json \
    renovate.json \
    rspack.config.js \
    tsconfig.json \
    vitest.*.ts \
    yarn.lock
EOF

COPY canvas ${CANVAS_HOME}

FROM ruby:${RUBY_VERSION}-slim-bookworm AS runner

ARG CANVAS_HOME
ARG CANVAS_USER=canvas

ENV RUBYLIB=${CANVAS_HOME}

RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends \
    git \
    libbrotli1 \
    libidn12 \
    libpq5 \
    libsqlite3-0 \
    libxmlsec1-openssl \
    shared-mime-info
apt-get clean
rm -rf /var/lib/apt/lists/*

groupadd ${CANVAS_USER}
useradd -g ${CANVAS_USER} -d ${CANVAS_HOME} ${CANVAS_USER}
EOF

COPY --from=builder --chown=${CANVAS_USER} ${GEM_HOME} ${GEM_HOME}
COPY --from=builder --chown=${CANVAS_USER} ${CANVAS_HOME} ${CANVAS_HOME}

WORKDIR ${CANVAS_HOME}

USER ${CANVAS_USER}

EXPOSE 3000

CMD [ "bundle", "exec", "rails", "server", "-b", "0.0.0.0" ]
