[tools]
actionlint = "latest"
ghalint = "latest"
hadolint = "latest"
lefthook = { version = "latest", postinstall = "lefthook install" }
node = "lts"
pnpm = "latest"
shellcheck = "latest"
task = "latest"
tombi = "latest"
zizmor = "latest"
