version: 3

tasks:
  default:
    cmd: task -a
    silent: true

  setup: &setup
    env:
      COMPOSE_PROJECT_NAME: canvas-lms-{{.DISTRIBUTION}}
      DISTRIBUTION: "{{.DISTRIBUTION}}"
    cmds:
      - cmd: docker compose run --rm web rails db:initial_setup
    requires:
      vars:
        - name: DISTRIBUTION
          enum:
            - alpine
            - debian

  run:
    <<: *setup
    cmds:
      - cmd: docker compose up -d {{.CLI_ARGS}}
      - cmd: docker compose exec -u root web sh -c "[ -d /opt/canvas/tmp/files ] && chown canvas:canvas /opt/canvas/tmp/files || true"

  shutdown:
    <<: *setup
    cmds:
      - cmd: docker compose down {{.CLI_ARGS}}

  logs:
    <<: *setup
    cmds:
      - cmd: docker compose logs -f {{.CLI_ARGS}}
