version: 3

env:
  COMPOSE_PATH_SEPARATOR: ":"

tasks:
  default:
    cmd: task -a
    silent: true

  setup:
    env:
      COMPOSE_FILE: compose.yml:compose.{{.DISTRIBUTION}}.yml
      COMPOSE_PROJECT_NAME: canvas-lms-{{.DISTRIBUTION}}
    cmd: docker compose run --rm app bundle exec rake db:initial_setup
    requires:
      vars:
        - name: DISTRIBUTION
          enum: [alpine, debian]

  run:
    env:
      COMPOSE_FILE: compose.yml:compose.{{.DISTRIBUTION}}.yml
      COMPOSE_PROJECT_NAME: canvas-lms-{{.DISTRIBUTION}}
    cmd: docker compose up -d {{.CLI_ARGS}}
    requires:
      vars:
        - name: DISTRIBUTION
          enum: [alpine, debian]

  shutdown:
    env:
      COMPOSE_FILE: compose.yml:compose.{{.DISTRIBUTION}}.yml
      COMPOSE_PROJECT_NAME: canvas-lms-{{.DISTRIBUTION}}
    cmd: docker compose down {{.CLI_ARGS}}
    requires:
      vars:
        - name: DISTRIBUTION
          enum: [alpine, debian]

  logs:
    env:
      COMPOSE_FILE: compose.yml:compose.{{.DISTRIBUTION}}.yml
      COMPOSE_PROJECT_NAME: canvas-lms-{{.DISTRIBUTION}}
    cmd: docker compose logs -f {{.CLI_ARGS}}
    requires:
      vars:
        - name: DISTRIBUTION
          enum: [alpine, debian]
