default: &default
  bucket_name: <%= ENV.fetch('AWS_S3_BUCKET') %>
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') %>
  region: <%= ENV.fetch('AWS_REGION') %>
  endpoint: <%= ENV.fetch('AWS_ENDPOINT') %>
  # If your storage use path-style bucket addresses.
  # force_path_style: true

production: *default

development: *default

test: *default
