default: &default
  storage: <%= ENV.fetch('CANVAS_LMS_STORAGE_TYPE') %>
  path_prefix: <%= ENV.fetch('CANVAS_LMS_STORAGE_PATH_PREFIX') %>

production: *default

development: *default

test: *default
