name: Lint Dockerfile

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    strategy:
      matrix:
        os:
          - alpine
          - debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.4.0
        with:
          dockerfile: Dockerfile.${{ matrix.os }}
          no-fail: true
