name: Lint Dockerfile

on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-slim
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - alpine
          - debian

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: Dockerfile.${{ matrix.os }}
          no-fail: true
