name: Trivy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Docker
    types: completed

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-slim
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - alpine
          - debian
        ruby-version:
          - "3.4"
          - "4.0"

    steps:
      - name: Run Trivy vulnerability scanner
        if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-ref: ${{ github.repository_owner }}/canvas-lms:ruby${{ matrix.ruby-version }}-${{ matrix.os }}
          scanners: vuln
          output: trivy.txt

      - name: Publish Trivy Output to Summary
        if: hashFiles('trivy.txt')
        run: |
          {
            echo '### Security Output'
            echo '<details><summary>Click to expand</summary>'
            echo ''
            echo '```terraform'
            cat trivy.txt
            echo '```'
            echo '</details>'
          } >> "${GITHUB_STEP_SUMMARY}"
